/* StorySpark – data.js
 * Content data (prompt entries per category) and UI strings.
 * i18n is structurally in place ("de"/"en" fields), but only "de" is
 * filled in for this first draft. "en" is left as `null` on purpose –
 * see concept.md, section "Offene Punkte".
 */

window.StorySpark = window.StorySpark || {};

(function () {
  // Small helper so every entry has a consistent shape without repeating
  // `{ en: null }` on every line below.
  function entries(deList) {
    return deList.map(function (de, i) {
      return { id: i + 1, de: de, en: null };
    });
  }

  StorySpark.data = {
    // "character": human + animal sub-pools mixed into one drawable list
    character: entries([
  // -- Menschen / Rollen (Berufe, Persönlichkeiten, soziale Rollen) --
  "Eine alte Frau",
  "Ein Kind",
  "Eine Wächterin",
  "Zwillinge",
  "Eine Fremde",
  "Ein Straßenmusikant",
  "Eine Postbotin",
  "Ein Uhrmacher",
  "Eine Reisende",
  "Ein Nachtwächter",
  "Eine Kapitänin",
  "Ein Erfinder",
  "Eine Köchin",
  "Ein Zirkusartist",
  "Eine Bibliothekarin",
  "Ein Gärtner",
  "Eine Lehrerin",
  "Ein Fischer",
  "Eine Schneiderin",
  "Ein Sammler",
  "Ein Zugbegleiter",
  "Ein Falkner",
  "Eine Glockengießerin",
  "Ein Steinmetz",
  "Ein Grenzgänger",
  "Ein Laternenanzünder",
  "Eine Seiltänzerin",
  "Ein Imker",
  "Eine Töpferin",
  "Ein Fährmann",
  "Eine Archivarin",
  "Ein Kartograf",
  "Eine Astronomin",
  "Ein Schäfer",
  "Eine Weberin",
  "Eine Astronautin",
  "Eine Krankenschwester",
  "Ein Arzt",
  "Eine Richterin",
  "Ein Schmuggler",
  "Eine Detektivin",
  "Ein Musiklehrer",
  "Eine Tänzerin",
  "Ein Bergsteiger",
  "Eine Forscherin",
  "Ein Eremit",
  "Eine Königin",
  "Ein Bettler",
  "Eine Diplomatin",
  "Ein Waisenjunge",
  "Eine Großmutter",
  "Ein Kutscher",
  "Eine Braut",
  "Ein Bräutigam",
  "Eine Witwe",
  "Ein Witwer",
  "Eine Priesterin",
  "Ein Mönch",
  "Eine Piratin",
  "Ein Söldner",
  "Eine Glücksspielerin",
  "Ein Zauberkünstler",
  "Eine Wahrsagerin",
  "Ein Schriftsteller",
  "Eine Journalistin",

  // -- Tiere (real, bewusst über die üblichen Verdächtigen hinaus) --
  "Ein Rabe",
  "Ein Fuchs",
  "Eine Schildkröte",
  "Ein Wal",
  "Eine Eule",
  "Ein Hase",
  "Eine Katze",
  "Ein Wolf",
  "Eine Motte",
  "Ein Maulwurf",
  "Ein Eichhörnchen",
  "Ein Pinguin",
  "Ein Esel",
  "Eine Ziege",
  "Ein Delfin",
  "Ein Bär",
  "Ein Papagei",
  "Ein Frosch",
  "Ein Reh",
  "Ein Dachs",
  "Eine Fledermaus",
  "Ein Luchs",
  "Eine Qualle",
  "Ein Seepferdchen",
  "Ein Tintenfisch",

  // -- Fantastische Wesen --
  "Ein Waldgeist",
  "Eine Nixe",
  "Ein Kobold",
  "Ein junger Drache",
  "Ein sprechender Baum",
  "Eine Wolkenfee",
  "Ein Steingolem",
  "Ein geflügeltes Pferd",
  "Ein Schneemensch",
  "Ein namenloses Zauberwesen",
]),

    // "timeOrSense": time + sense-impression sub-pools mixed
    timeOrSense: entries([
  // -- Zeit --
  "Kurz vor Sonnenaufgang",
  "Mitten in der Nacht",
  "An einem Sonntagnachmittag",
  "Vor langer Zeit",
  "Der letzte Tag von etwas",
  "Mitten im Winter",
  "Kurz vor Ladenschluss",
  "Am späten Abend",
  "Beim ersten Schnee",
  "Eine vergessene Stunde",
  "Der erste Tag von etwas",
  "In hundert Jahren",
  "Am Morgen des Festtags",
  "Zur Erntezeit",
  "An einem Regentag",
  "In der Mittagspause",
  "Kurz nach Mitternacht",
  "Im Morgengrauen",
  "An einem Feiertag",
  "Zwischen zwei Zügen",
  "In der Dämmerung",
  "An einem gewöhnlichen Dienstag",
  "Am Tag der Abreise",
  "In der Stunde vor der Prüfung",
  "Am Vorabend eines Festes",
  "Im tiefsten Sommer",
  "An einem Tag ohne Kalender",
  "Kurz vor der Ernte",
  "Am ersten Schultag",
  "In der Pause zwischen zwei Gewittern",
  "An einem Tag, der sich wiederholt",
  "Beim Wechsel der Jahreszeiten",
  "In der letzten Stunde des Jahres",
  "An einem Tag, an dem nichts passieren sollte",
  "Kurz vor dem Umzug",
  "Am Tag der Rückkehr",
  "In der Woche vor der Hochzeit",
  "An einem Tag ohne Uhr",
  "Zwischen Traum und Erwachen",
  "Am Ende einer langen Reise",
  "Kurz vor der Sperrstunde",
  "An einem stillen Feiertagmorgen",
  "In der Zeit, in der niemand hinschaut",
  "Am Tag, bevor alles anders wird",
  "In der Stunde des Sonnenuntergangs",
  "An einem Tag mit doppeltem Regenbogen",
  "Kurz vor der Flut",
  "In der Nacht der Sommersonnenwende",
  "An einem Tag, der zu lang wird",
  "Beim letzten Läuten der Glocke",

  // -- Sinneseindruck --
  "Ein Geruch nach Regen",
  "Ein Geräusch aus der Ferne",
  "Etwas Warmes",
  "Ein plötzliches Licht",
  "Ein Geschmack nach Salz",
  "Fernes Lachen",
  "Ein leises Summen",
  "Ein Funkeln",
  "Eine ungewohnte Kälte",
  "Der Klang von Glocken",
  "Ein Geruch nach frisch gebackenem Brot",
  "Ein Geräusch, das immer lauter wird",
  "Ein Licht, das plötzlich angeht",
  "Ein Klang wie Musik unter Wasser",
  "Musik aus der Ferne",
  "Ein Kribbeln vor Aufregung",
  "Ein Geräusch, das man nicht zuordnen kann",
  "Ein Geruch nach Meer",
  "Etwas Weiches unter den Füßen",
  "Ein Funkeln im Augenwinkel",
  "Ein Geruch nach nassem Laub",
  "Ein Kratzen an der Tür",
  "Ein Schatten, der sich bewegt",
  "Ein Geschmack nach Zimt",
  "Ein Geruch nach altem Papier",
  "Ein Ticken, das nicht aufhört",
  "Ein Windstoß aus dem Nichts",
  "Ein Geräusch wie brechendes Eis",
  "Ein Geruch nach Rauch",
  "Eine Stimme, die den eigenen Namen ruft",
  "Ein Schauer über den Rücken",
  "Ein Geschmack nach Honig",
  "Ein Klopfen, das aus dem Nichts kommt",
  "Ein Duft nach Lavendel",
  "Ein Geräusch wie flüsterndes Gras",
  "Ein Kribbeln in den Fingerspitzen",
  "Ein Geruch nach frisch gemähtem Gras",
  "Ein Licht, das flackert und wieder verschwindet",
  "Ein Geschmack nach Minze",
  "Ein Geräusch wie ferner Donner",
  "Eine plötzliche Stille",
  "Ein Geruch nach Benzin und Staub",
  "Eine Wärme, die von nirgendwo kommt",
  "Ein Klang, der an Kindheit erinnert",
  "Ein Geräusch wie Schritte auf Kies",
  "Ein Geschmack nach Rost",
  "Ein Duft nach frisch gewaschener Wäsche",
  "Ein Glitzern auf nasser Straße",
  "Ein Geräusch wie ein tiefer Atemzug",
  "Ein Frösteln ohne erkennbaren Grund",
]),

    object: entries([
  "Ein Schlüssel",
  "Ein offener Brief",
  "Eine stehengebliebene Uhr",
  "Ein Koffer",
  "Ein Spiegel",
  "Eine Kerze",
  "Ein Foto",
  "Ein Ring",
  "Eine Landkarte",
  "Ein Buch",
  "Ein zerbrochenes Glas",
  "Eine Flasche mit Zettel darin",
  "Ein altes Radio",
  "Ein Kompass, der nicht funktioniert",
  "Eine Muschel",
  "Ein Regenschirm",
  "Ein Kartenspiel mit fehlender Karte",
  "Eine Puppe",
  "Ein Fernglas",
  "Ein Fahrrad ohne Kette",
  "Eine Schachtel mit Knöpfen",
  "Ein Zugticket",
  "Ein Amulett",
  "Eine Taschenlampe mit schwachem Licht",
  "Ein handgeschriebenes Rezept",
  "Ein Paar alte Schuhe",
  "Ein leerer Vogelkäfig",
  "Eine Schallplatte ohne Hülle",
  "Ein Tagebuch mit fehlenden Seiten",
  "Ein Werkzeugkasten",
  "Ein Feuerzeug",
  "Eine Truhe mit Vorhängeschloss",
  "Ein Teleskop",
  "Ein gefaltetes Stück Papier",
  "Ein altes Telefon",
  "Ein Globus",
  "Ein Blumenstrauß, schon welk",
  "Eine Nähmaschine",
  "Ein Segelboot in einer Flasche",
  "Eine Taschenuhr an einer zerrissenen Kette",
  "Ein Stapel ungeöffneter Briefe",
  "Ein Set Aquarellfarben",
  "Ein Schachbrett mit nur wenigen Figuren",
  "Eine Thermoskanne",
  "Ein Notizbuch voller Zahlen",
  "Ein Anhänger in Form eines Mondes",
  "Eine alte Schreibmaschine",
  "Ein Bund vertrockneter Kräuter",
  "Ein Röntgenbild",
  "Ein Schlüsselbund",
]),

    place: entries([
      "Ein großes Haus",
      "Ein Bahnsteig",
      "Ein Garten hinter einer Mauer",
      "Ein Dachboden",
      "Eine Brücke",
      "Ein Wald",
      "Ein Hafen",
      "Ein leerer Marktplatz",
      "Eine Bibliothek",
      "Ein Keller",
    ]),

    mood: entries([
  "Ein großes Haus",
  "Ein Bahnsteig",
  "Ein Garten hinter einer Mauer",
  "Ein Dachboden",
  "Eine Brücke",
  "Ein Wald",
  "Ein Hafen",
  "Ein leerer Marktplatz",
  "Eine Bibliothek",
  "Ein Keller",
  "Ein verlassener Leuchtturm",
  "Eine Dorfbäckerei vor Ladenöffnung",
  "Ein U-Bahnhof kurz vor Betriebsschluss",
  "Eine Lichtung mitten im Wald",
  "Ein Freibad im Herbst",
  "Eine Werkstatt voller angefangener Projekte",
  "Ein Krankenhausflur",
  "Ein Flughafenterminal nachts",
  "Ein Weinberg",
  "Eine Kapelle am Straßenrand",
  "Ein Vergnügungspark außerhalb der Saison",
  "Ein Fischmarkt in aller Frühe",
  "Eine Berghütte",
  "Ein Aufzug, der stecken bleibt",
  "Ein Museum nach Schließzeit",
  "Ein Zugabteil bei Nacht",
  "Ein Gewächshaus",
  "Ein Strand bei Ebbe",
  "Ein Hinterhof mit Wäscheleinen",
  "Eine Tankstelle an einer einsamen Straße",
  "Ein Klassenzimmer in den Ferien",
  "Ein Fährdeck",
  "Ein Weinkeller",
  "Ein Dorf, das bald umgesiedelt wird",
  "Eine Höhle mit Echo",
  "Ein Rummelplatz beim Aufbau",
  "Ein Gasthof an der Kreuzung",
  "Ein Trödelladen",
  "Eine Turnhalle nach Schulschluss",
  "Ein Hausboot",
  "Ein alter Bahnhof, nicht mehr in Betrieb",
  "Ein Gemüsegarten hinter einem Krankenhaus",
  "Eine Seilbahnstation",
  "Ein Antiquariat",
  "Eine Dachterrasse über der Stadt",
  "Ein Weizenfeld kurz vor dem Sturm",
  "Eine Notaufnahme, gerade ruhig",
  "Ein Zeltlager im Regen",
  "Ein Kloster mit Blick aufs Tal",
  "Eine Bushaltestelle mitten im Nirgendwo",
]),
  };

  // UI strings. "en" is intentionally left empty ("") rather than filled –
  // app.js falls back to "de" whenever an "en" string is empty.
  StorySpark.strings = {
    de: {
      appName: "Schreibfunke",
      tagline: "Ein Impuls fürs kreative Schreiben. Für jeden Tag einen, für jeden Besucher gleich. Geh und schreib etwas - eine Kurzgeschichte, eine Szene, einen Vers, was du willst.",
      todayLabel: "Heute",
      nextInPrefix: "Nächster Funke in ca.",
      nextInHoursSuffix: "Std.",
      nextInSoon: "Neuer Funke gleich",
      doneButton: "Geschafft",
      doneButtonActive: "Geschafft ✓",
      dayNavBackLabel: "Vorherigen Tag anzeigen",
      dayNavForwardLabel: "Zu heute zurück",
      langSwitch: "DE / EN",
    },
    en: {
      appName: "Story Spark",
      tagline: "",
      todayLabel: "",
      nextInPrefix: "",
      nextInHoursSuffix: "",
      nextInSoon: "",
      doneButton: "",
      doneButtonActive: "",
      dayNavBackLabel: "",
      dayNavForwardLabel: "",
      langSwitch: "DE / EN",
    },
  };

  // Tunable knobs for the draw logic (see draw.js). Kept here so they're
  // easy to find and adjust without touching the algorithm itself.
  StorySpark.config = {
    dailyLimit: 5,
    mainCategories: ["character", "timeOrSense"],
    extraCategories: ["object", "place", "mood"],
    mainAppearProbability: 0.7,
    extraAppearProbability: 0.4,
    duplicateProbability: 0.12,
  };
})();
